### ISSUE TITLE
Error al agregar sequencias filttradas

### ISSUE THREAD

**Issue by kavilac** [irgNemo/compendium#1]
Mencionar que gene o product funciona bien. El error está al momento de agregar, como en una misma secuencia se pueden encontrar todos o vario valores contenidos en tag_value por eso agrega la secuencia más veces.
En este ejemplo estoy buscando en una sola secuencia las secciones E6|E7|E1
Posible solición activar una bandera en lugar de agregar a la lista, fuera del for feature verificar si se activo la bandera, de ser así entonces agregar a la lista.
![screenshot from 2016-11-15 14-02-59](https://cloud.githubusercontent.com/assets/14955724/20321811/5bbf371a-ab3c-11e6-83ef-f5035fb73c90.png)

**Comment by irgNemo** [comment]
Hola Karla,

Acabo de subir el cambio con la función, es mas o menos como lo mencionas en tu solución propuesta. Checalo y me dices que te parece.

**Comment by kavilac** [comment]
Hola profe. 
Hice la rama de correccionUtil ahí puse la propuesta.
Acabo de ver que usted ya subio uno aunque es algo diferente. Igual el que hice solo lo he probado para una secuencia que contiene las 3 (como en el ejemplo de la imagen) y ya no la repite 3 veces.

**Comment by irgNemo** [comment]
Hola,
Ok, la reviso. Tu también hazlo y trata de ver cual es más clara. Esta bien que haya dos diferentes implementaciones, nos quedaremos con la que mejor nos convenga.
Subi un archivo llamado hpv_type6.gb, este tiene una secuencia que no tiene el gen E7, pruebalo con este archivo y vez que pasa. 
También prueba en tu programa si al pasar nombre de los genes (E7 y E6) en la función validaORFs los ogue haciendo bien.

**Comment by kavilac** [comment]
Hola profe. 
Ya probe y estos son los resultados que he obtenido:
El archivo contiene 10 secuencias de las cuales todas tienen E6.
![screenshot from 2016-11-19 21-16-25](https://cloud.githubusercontent.com/assets/14955724/20460079/a555662e-ae9d-11e6-9076-b6584952bb19.png)
7 secuencias tiene E7
![screenshot from 2016-11-19 21-17-39](https://cloud.githubusercontent.com/assets/14955724/20460080/a559d948-ae9d-11e6-8fd0-129fc66d7e85.png)
6 secuencias contienen L1
![screenshot from 2016-11-19 21-19-13](https://cloud.githubusercontent.com/assets/14955724/20460096/00c30caa-ae9e-11e6-95d8-f8af7d7adb7f.png)
Y 7 secuencias contienen L1 ó E7
![screenshot from 2016-11-19 21-21-14](https://cloud.githubusercontent.com/assets/14955724/20460101/406bcee6-ae9e-11e6-9334-57d6ca326b10.png)
Entonces funciona para filtar secuencias que contengan un tipo de seccion especifico y para secuencias que contienen o una u otra ... 
NO veo funcionabilidad para obtener secucncias que en la misma secuencia contenga ambas.
Saludos.
