### ISSUE TITLE
Escritura de PDF

### ISSUE THREAD

**Issue by irgNemo** [irgNemo/compendium#2]
Hola Karla,

Como te comentaba en persona, la tarea para estos días será la impresión (correcta) en PDF de los alineamientos junto con su árbol filogenético. El lunes platicamos para ver cual crees que es el camino a seguir para la impresión del árbol. 

Saludos y nos vemos el lunes

Israel Román Godínez

**Comment by kavilac** [comment]
Hola Dr. Israel. 
Buenas noches, una propuesta está en la rama de reportes. Generé la imagen del arbol en base a "pylab" (es necesaria su instalación) recomendado por la bibliografia de biopython y agregue esa imagen al pdf. Según estuve leyendo tambien puede guardarla directaente en pdf pero ocupo trabajar un poco más en eso.  
Saludos.
Karla Avila.

**Comment by irgNemo** [comment]
Hola Karla,

Ya vi a que te referías con los ateriscos. Esto que esta pasando no se resuelve con la tipografía. Vamos pensando como se haría. Por el momento voy revisando el código que estas haciendo. 

Gracias
Israel Román

**Comment by kavilac** [comment]
Hola Dr. Israel.
Se ha solucionado exitosamente la generación de reportes. 
Saludos.
Karla Avila
